### ISSUE TITLE
Can I get write right?

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-developmental-ontology#1]
While we are developing FBDV at least. @Clare72 @dosumis

**Comment by matentzn** [comment]
Just to clarify, I need (temporary) write rights to the fbdv, dpo, and fbcv repos

**Comment by dosumis** [comment]
@Clare72  - I don't  appear to have permissions.  Can set (and add me too  while you're at  it?)

**Comment by Clare72** [comment]
Done - Nico, looks like you already had write access for fbcv, I have added you both for dpo and fbdv.
