### ISSUE TITLE
Make sure ro-eco subset works properly (obo edit load fail)

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-developmental-ontology#5]

**Comment by matentzn** [comment]
Wow this is a very general problem we need to sort with a hack, for now. sorry. I made a general ODK ticket, buit it will be 2020 before we can solve it.

**Comment by Clare72** [comment]
@matentzn is this fixed now? I see that ro-eco now has a subsetdef.
Can I stop removing 'subset[:][ ]ro[-]eco' from the FlyBase ontologies?

**Comment by matentzn** [comment]
I dont know -> I have not fixed this!

**Comment by Clare72** [comment]
Was the problem that it didn't have a subsetdef? Because it seems that it does have one now.

https://github.com/FlyBase/drosophila-developmental-ontology/blob/54c8a005371a6263fb2085d111a57dae591f4628/fbdv-simple.obo#L20

**Comment by matentzn** [comment]
The problem was somehow that the OBO parser threw and error when loading the OBO version. So you can test whether it works by running a ROBOT command which reads in the OBO file (doesn't matter what else it does). If this works, then its fine!

**Comment by Clare72** [comment]
Yes, it now opens in oboedit without removing 'subset[:][ ]ro[-]eco'

**Comment by Clare72** [comment]
this was the problem before (I think protege could still open it)

**Comment by matentzn** [comment]
Great! Can be ditched then!
