### ISSUE TITLE
general question about precise bounds for instar stages

### ISSUE THREAD

**Issue by ANiknejad** [FlyBase/drosophila-developmental-ontology#86]
Hello Damien @gouttegd 
I hope you are fine.
I would love to have your help clearly understanding this definition:

[Term]
id: FBdv:00005338
name: second instar larval stage
namespace: FlyBase_development_CV
def: "**The second larval instar begins at the first larval molt and ends at the second larval molt.** Larvae are actively feeding and crawling in the food. Distinct anterior spiracles are present as enlargements at the end of the tracheal trunk, but not open to the outside; posterior spiracles have three openings each, and four groups of small unbranched hairs. The salivary glands extend to the first abdominal segment, and have cells that are uniform in size. Mouth hooks typically have two or three teeth. Duration at 25 degrees C: approximately 23 hours (49-72 hours after egg laying; 25-48 hours after hatching)." [FlyBase:FBrf0007733]
comment: Temporal ordering number - 420.
synonym: "L2" EXACT []
synonym: "second instar larva" EXACT []
xref: UBERON:8000001
is_a: FBdv:00007012 ! life stage
relationship: immediately_preceded_by FBdv:00005337 ! first instar larval stage
relationship: immediately_precedes FBdv:00005339 ! third instar larval stage
relationship: substage_of FBdv:00005336 ! larval stage

Does it mean, this stage starts at post-molt stage of the first larval molt, and ends after ecdysis of second larval molt?
I need to have a clear view of what molt stages are included in the definition of an instar stage.

Do you agree with the following proposition:
an 'instar stage' encompasses:

-  post-molt stage
-  intermolt stage
-  pre-ecdysis stage
-  ecdysis stage (so ecdysis is the last molt stages of every instar)

With a distinction for the terminal instar (if any) which ends at death and not at ecdysis, and only has post-molt and inter-molt.

**Comment by gouttegd** [comment]
Hello Anne,

> Does it mean, this stage starts at post-molt stage of the first larval molt, and ends after ecdysis of second larval molt?

That’s my understanding as well, yes. Do you want that to be made clearer in the definition?

> an 'instar stage' encompasses:
>
> * post-molt stage
> * intermolt stage
> * pre-ecdysis stage
> * ecdysis stage (so ecdysis is the last molt stages of every instar)

Sounds sensible to me. Do you require such terms to be added for each stage? Or merely that the definition makes clear what the stage encompasses?

**Comment by ANiknejad** [comment]
Hi Damien, thank you very much for your feedback. Actually I only needed your approval regarding the meaning of the definition, because I am currently involved in a project where I have to create ontologies for some crustacean species. So far the FBdv classes are ok for me, just happy to see we understand the same way.
